sudo: false

language: python

notifications:
  email:
    - michele@openquake.org
    - gweather@gfz-potsdam.de

python:
 - "3.5"

addons:
  apt:
    packages:
    - git

install:
  # Check if the same branch exists on 'oq-engine'
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" != "" ]; then BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; else BRANCH=$TRAVIS_BRANCH; fi
  - if [ "$(git ls-remote --heads https://github.com/gem/oq-engine.git ${BRANCH})" == "" ]; then
      BRANCH='master';
    fi;
  # Clone 'oq-engine'
  - git clone -q -b $BRANCH --depth=1 https://github.com/gem/oq-engine.git && echo "Running against oq-engine/${BRANCH}"
  # Make sure pip is up-to-date and has support for wheels
  - pip -q install -U pip
  # Install oq-engine dependencies
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -r oq-engine/requirements-py27-linux64.txt;
    elif [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install -r oq-engine/requirements-py35-linux64.txt; 
    elif [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -r oq-engine/requirements-py36-linux64.txt; 
    else echo "Python not supported" && exit 1; fi
  - pip install -e oq-engine/
  - pip install -e .

script:
  - nosetests -vsx tests/hazard/conditional_simulation_test.py
  - nosetests -vsx tests/intensity_measures_test.py
  - nosetests -vsx tests/trellis/trellis_test.py
  - nosetests -vsx tests/parsers/asa_parser_test.py
  - nosetests -vsx tests/parsers/esm_flatfile_parser_test.py
  - nosetests -vsx tests/residuals/residuals_test.py
